version: '3.8'
services:
  app:
    volumes:
      - ./:/var/www/app
    build:
      context: ./_docker/app
      dockerfile: Dockerfile

  nginx:
    image: nginx:stable
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/app
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
      - mysql
      - phpmyadmin

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    env_file:
      - ./_docker/mysql/mysql.env
    healthcheck:
       test: [ "CMD-SHELL", "mysqladmin --silent --wait=30 ping" ]
       interval: 10s
       retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  mysqldata:
